# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'API_Classes_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for API_Classes_Swift
pod 'Alamofire', '~> 4.4’
pod 'AlamofireImage', '~> 3.2'
pod 'TrustKit'
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'


end
